# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  WORKFLOW_VAR: 'minha variavel no escopo do workflow'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 12
      JOB_VAR: 'minha variavel no escopo do job'
      
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2.3.4
    
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: 1- Step com variável de ambiente
      env:
        STEP_VAR: 'minha variavel no escopo do step'
      run: echo $STEP_VAR
      
    - name: 2- Step com variável de ambiente
      run: echo $STEP_VAR
      
    - run: echo $JOB_VAR
    - run: echo $WORKFLOW_VAR
